{% set name = "msoffcrypto-tool" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2f334cecd19eaa7426f26fc6f661a30268d4817e48d4c006708b4b29dcab6d7f

build:
  entry_points:
    - msoffcrypto-tool = msoffcrypto.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - cryptography >=2.3
    - olefile >=0.45
    - python >=3.6,<4.0

test:
  imports:
    - msoffcrypto
  commands:
    - pip check
    - msoffcrypto-tool --help
  requires:
    - pip

about:
  home: https://github.com/nolze/msoffcrypto-tool
  summary: Python tool and library for decrypting MS Office files with passwords or other keys
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
